/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ProjectPBO;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAMA
 */
public class Kasir extends javax.swing.JFrame {

    private String memberid = null;
    private String barangid = null;
    private String transaksiid = null;
    private String harga = null;
    private int totalharga = 0;
    private int jumlah = 0;
    private int kembalian = 0;
    int[] idBarang = new int[100];
    private int index = 0;
    
    
 
    
    
    
    private void Cbid() throws SQLException{
        String sql = "SELECT * FROM member";
        try{
            java.sql.Connection conn = (Connection)Config.configDB(); 
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            Statement stm = (Statement)conn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while(rs.next()){
                cbid.addItem(rs.getString(2));
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void admin(){
        String id = Sesi.get_id();
        String sql ="SELECT * FROM pegawai WHERE user_id= "+id+";";
        
        try{
            java.sql.Connection conn = (Connection)Config.configDB();
            java.sql.PreparedStatement pstm;
            pstm = conn.prepareStatement(sql);
            ResultSet rs = pstm.executeQuery();
            
            while(rs.next()){
                jadmin.setText(rs.getString("pegawai_nama"));
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void ShowData(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn ("Nama barang");
        model.addColumn ("Harga barang");
        model.addColumn ("Jumlah");
        model.addColumn ("Total harga");
        try{
            String sql = "SELECT barang.barang_nama, detail_transaksi.dtransaksi_harga, detail_transaksi.dtransaksi_jumlah, (detail_transaksi.dtransaksi_jumlah*detail_transaksi.dtransaksi_harga) AS 'Total harga'"
                    + "FROM detail_transaksi INNER JOIN barang ON barang.barang_id = detail_transaksi.barang_id WHERE transaksi_id = "+transaksiid+";";
            java.sql.Connection conn;
            conn = (Connection)Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),"Rp."+res.getString(2), res.getString(3),"Rp."+res.getString(4)});
                
            }
            tabel.setModel(model);
            
        }catch(SQLException e){
            System.out.println("Error "+ e.getMessage());
        }
        
    }
    
    
    
    public Kasir() throws SQLException {
        initComponents();
        admin();
        ShowData();
        Cbid();
        txtnamabarang.setText(Sesi.get_namabarang());
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbtransaksi = new javax.swing.JTable();
        clGradientPanel1 = new ProjectPBO.ClGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jadmin = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        cbid = new javax.swing.JComboBox<>();
        btnbuat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtjumlah = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        btninput = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        txtbayar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtkembalian = new javax.swing.JTextField();
        btnselesai = new javax.swing.JButton();
        txtnamabarang = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        tbtransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbtransaksi);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel1.setText("Kasir");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Admin : ");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Nama Member");

        jadmin.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        jButton4.setText("Logout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cbid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbidItemStateChanged(evt);
            }
        });
        cbid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbidActionPerformed(evt);
            }
        });

        btnbuat.setText("Buat");
        btnbuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuatActionPerformed(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabel);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Jumlah barang");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Nama barang");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Harga");

        txtjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahActionPerformed(evt);
            }
        });

        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });

        btninput.setText("Input");
        btninput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninputActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Total transaksi");

        txtbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbayarActionPerformed(evt);
            }
        });
        txtbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbayarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbayarKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Bayar");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setText("Kembalian");

        txtkembalian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtkembalianKeyReleased(evt);
            }
        });

        btnselesai.setText("Selesai");
        btnselesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselesaiActionPerformed(evt);
            }
        });

        txtnamabarang.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                txtnamabarangMouseDragged(evt);
            }
        });
        txtnamabarang.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                txtnamabarangMouseWheelMoved(evt);
            }
        });
        txtnamabarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnamabarangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtnamabarangMouseEntered(evt);
            }
        });
        txtnamabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamabarangActionPerformed(evt);
            }
        });
        txtnamabarang.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtnamabarangPropertyChange(evt);
            }
        });
        txtnamabarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnamabarangKeyReleased(evt);
            }
        });

        jButton1.setText("Cek");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clGradientPanel1Layout = new javax.swing.GroupLayout(clGradientPanel1);
        clGradientPanel1.setLayout(clGradientPanel1Layout);
        clGradientPanel1Layout.setHorizontalGroup(
            clGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clGradientPanel1Layout.createSequentialGroup()
                        .addGroup(clGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(clGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(clGradientPanel1Layout.createSequentialGroup()
                        .addGroup(clGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(clGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(354, 354, 354))
                            .addGroup(clGradientPanel1Layout.createSequentialGroup()
                                .addGroup(clGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(clGradientPanel1Layout.createSequentialGroup()
                                        .addGroup(clGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addGroup(clGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel7))
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(clGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtjumlah)
                                            .addComponent(txtharga)
                                            .addComponent(txttotal)
                                            .addComponent(txtbayar)
                                            .addComponent(txtkembalian)
                                            .addGroup(clGradientPanel1Layout.createSequentialGroup()
                                                .addComponent(txtnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clGradientPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(clGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnbuat, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btninput, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnselesai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        clGradientPanel1Layout.setVerticalGroup(
            clGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clGradientPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(clGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(clGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(clGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(clGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clGradientPanel1Layout.createSequentialGroup()
                        .addGroup(clGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnbuat)
                        .addGap(22, 22, 22)
                        .addGroup(clGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(clGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(clGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btninput)
                        .addGap(25, 25, 25)
                        .addGroup(clGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(clGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(clGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnselesai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(clGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnselesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselesaiActionPerformed
        if(kembalian > -1){
            String sql = "UPDATE `transaksi` SET `transaksi_total` = "+totalharga+" WHERE `transaksi`.`transaksi_id` = "+transaksiid+";";
            try{
                java.sql.Connection conn = (Connection)Config.configDB();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.execute();
                JOptionPane.showMessageDialog(null, "Berhasil");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            memberid = null;
            barangid = null;
            transaksiid = null;
            totalharga = 0;
            Sesi.set_namabarang(null);
            this.dispose();
            try {
                new Kasir().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Kasir.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Uangnya kurang bos..");
        }
    }//GEN-LAST:event_btnselesaiActionPerformed

    private void txtbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbayarActionPerformed
        
    }//GEN-LAST:event_txtbayarActionPerformed

    private void btninputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninputActionPerformed
        int tharga = 0;
        int i;
        int result = 0;
        for(i = 0; i<=index;i++){
            if(idBarang[i] == Integer.parseInt(barangid)){
                result += 1;
            }
            System.out.print(idBarang[i]);
        }
        System.out.print("="+barangid+"\n");
        if(result>0){
            String sql = "UPDATE detail_transaksi SET dtransaksi_jumlah = (dtransaksi_jumlah+"+txtjumlah.getText()+") WHERE barang_id = "+barangid+";";
            try{
                java.sql.Connection conn = (Connection)Config.configDB();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.execute();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }

            sql = "SELECT SUM(dtransaksi_jumlah*dtransaksi_harga) FROM detail_transaksi WHERE transaksi_id = "+transaksiid+"";
            try{
                java.sql.Connection conn = (Connection)Config.configDB();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                Statement stm = (Statement)conn.createStatement();
                ResultSet rs = stm.executeQuery(sql);
                while(rs.next()){
                    totalharga = rs.getInt(1);
                }
                txttotal.setText("Rp."+Integer.toString(totalharga));
                ShowData();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }

        } else if(result == 0){
            idBarang[index] = Integer.parseInt(barangid);
            index += 1;
            String sql = "INSERT INTO detail_transaksi VALUES ("+transaksiid+","+barangid+", now(), "+txtjumlah.getText()+","+harga+");";
            try{
                java.sql.Connection conn = (Connection)Config.configDB();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.execute();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }

            sql = "SELECT SUM(dtransaksi_jumlah*dtransaksi_harga) FROM detail_transaksi WHERE transaksi_id = "+transaksiid+"";
            try{
                java.sql.Connection conn = (Connection)Config.configDB();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                Statement stm = (Statement)conn.createStatement();
                ResultSet rs = stm.executeQuery(sql);
                while(rs.next()){
                    totalharga = rs.getInt(1);
                }
                txttotal.setText("Rp."+Integer.toString(totalharga));
                ShowData();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        

    }//GEN-LAST:event_btninputActionPerformed

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaActionPerformed

    private void txtjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlahActionPerformed

    private void btnbuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuatActionPerformed

        String pegawai = Sesi.get_pegawai_id();
        String sql = "INSERT INTO `transaksi`( `pegawai_id`, `member_id`, `transaksi_total`, `transaksi_tanggal`) VALUES ("+pegawai+","+memberid+", 0, now());";
        try{
            java.sql.Connection conn = (Connection)Config.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        sql = "SELECT * FROM transaksi ORDER BY transaksi_id DESC LIMIT 1;";
        try{
            java.sql.Connection conn = (Connection)Config.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            Statement stm = (Statement)conn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while(rs.next()){
                transaksiid = rs.getString(1);
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

        
    }//GEN-LAST:event_btnbuatActionPerformed

    private void cbidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbidActionPerformed
        String sql = "SELECT * FROM member WHERE member_nama = '"+cbid.getSelectedItem()+"';";
        try{
            java.sql.Connection conn = (Connection)Config.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            Statement stm = (Statement)conn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while(rs.next()){
                memberid = rs.getString(1);
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cbidActionPerformed

    private void cbidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbidItemStateChanged

    }//GEN-LAST:event_cbidItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Sesi.set_Level(null);
        Sesi.set_id(null);
        Sesi.set_pegawai_id(null);
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtnamabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamabarangActionPerformed
        
    }//GEN-LAST:event_txtnamabarangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new barang().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnamabarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnamabarangMouseClicked
       
    }//GEN-LAST:event_txtnamabarangMouseClicked

    private void txtnamabarangMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_txtnamabarangMouseWheelMoved
         
    }//GEN-LAST:event_txtnamabarangMouseWheelMoved

    private void txtnamabarangMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnamabarangMouseDragged
        
    }//GEN-LAST:event_txtnamabarangMouseDragged

    private void txtnamabarangPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtnamabarangPropertyChange
        
    }//GEN-LAST:event_txtnamabarangPropertyChange

    private void txtnamabarangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnamabarangMouseEntered
        txtnamabarang.setText(Sesi.get_namabarang());
        String sql = "SELECT * FROM barang WHERE barang_nama = '"+txtnamabarang.getText()+"';";
        int temp;
        try{
            java.sql.Connection conn = (Connection)Config.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            Statement stm = (Statement)conn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while(rs.next()){
                temp = Integer.parseInt(rs.getString(5)) + Integer.parseInt(rs.getString(5))*10/100;
                harga = Integer.toString(temp) ;
                barangid = rs.getString(1);
                txtharga.setText("Rp."+harga);
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_txtnamabarangMouseEntered

    private void txtbayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbayarKeyTyped
        
    }//GEN-LAST:event_txtbayarKeyTyped

    private void txtkembalianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkembalianKeyReleased
        
    }//GEN-LAST:event_txtkembalianKeyReleased

    private void txtbayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbayarKeyReleased
        int bayar = Integer.valueOf(txtbayar.getText());
        int kembali = bayar - totalharga;
        kembalian = kembali;
        txtkembalian.setText("Rp."+kembali);
    }//GEN-LAST:event_txtbayarKeyReleased

    private void txtnamabarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamabarangKeyReleased
        Sesi.set_namabarang(txtnamabarang.getText());
        String sql = "SELECT * FROM barang WHERE barang_nama = '"+txtnamabarang.getText()+"';";
        int temp;
        try{
            java.sql.Connection conn = (Connection)Config.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            Statement stm = (Statement)conn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while(rs.next()){
                temp = Integer.parseInt(rs.getString(5)) + Integer.parseInt(rs.getString(5))*10/100;
                harga = Integer.toString(temp) ;
                barangid = rs.getString(1);
                txtharga.setText("Rp."+harga);
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_txtnamabarangKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Kasir().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Kasir.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuat;
    private javax.swing.JButton btninput;
    private javax.swing.JButton btnselesai;
    private javax.swing.JComboBox<String> cbid;
    private ProjectPBO.ClGradientPanel clGradientPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jadmin;
    private javax.swing.JTable tabel;
    private javax.swing.JTable tbtransaksi;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtkembalian;
    private javax.swing.JTextField txtnamabarang;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables

}
